name: mayavi-env
channels:
  - defaults
dependencies:
  - tzdata=2022a
  - intel-openmp=2021.4.0
  - numpy=1.21.5
  - pcre=8.45
  - openssl
  - numpy-base=1.21.5
  - qt=5.9.7
  - _libgcc_mutex=0.1
  - readline=8.1.2
  - wheel=0.37.1
  - gstreamer=1.14.0
  - libffi=3.3
  - mkl_fft=1.3.1
  - scipy=1.7.3
  - pip=21.2.4
  - freetype=2.11.0
  - libgomp=9.3.0
  - gst-plugins-base=1.14.0
  - mkl=2021.4.0
  - ca-certificates
  - libpng=1.6.37
  - blas=1.0
  - mkl_random=1.2.2
  - expat=2.4.4
  - python=3.9.12
  - zlib=1.2.12
  - setuptools=61.2.0
  - libxml2=2.9.12
  - ncurses=6.3
  - pyqt=5.9.2
  - icu=58.2
  - sip=4.19.13
  - six=1.16.0
  - jpeg=9e
  - libgfortran4=7.5.0
  - mkl-service=2.4.0
  - tk=8.6.11
  - certifi
  - xz=5.2.5
  - fontconfig=2.13.1
  - libuuid=1.0.3
  - dbus=1.13.18
  - sqlite=3.38.3
  - pandas
  - cartopy
